trigger:
- master

schedules:
- cron: '0 0 * * *'
  displayName: 'Daily build'
  branches:
    include:
    - master
  always: true

stages:

- stage: lint
  jobs:
  - template: azure-pipelines-lint.yaml

- stage: test
  jobs:
  - template: azure-pipelines-test-azure.yaml
    parameters:
      pythonMajorVersion: '3'
      pythonMinorVersion: '5'
  - template: azure-pipelines-test-azure.yaml
    parameters:
      pythonMajorVersion: '3'
      pythonMinorVersion: '6'
  - template: azure-pipelines-test-azure.yaml
    parameters:
      osType: 'macos'
  - template: azure-pipelines-test-azure.yaml
    parameters:
      osType: 'windows'
  - template: azure-pipelines-test-azure.yaml
    parameters:
      storageKind: 'BlobStorage'
  - template: azure-pipelines-test-azure.yaml
    parameters:
      storageKind: 'Storage'
  - template: azure-pipelines-test-azure.yaml
  - template: azure-pipelines-test-container.yaml
