trigger:
- master

stages:

- stage: lint
  jobs:
  - template: azure-pipelines-lint.yaml

- stage: test
  jobs:
  - template: azure-pipelines-test-azure.yaml
    parameters:
      pythonMajorVersion: '3'
      pythonMinorVersion: '5'
  - template: azure-pipelines-test-azure.yaml
    parameters:
      pythonMajorVersion: '3'
      pythonMinorVersion: '6'
  - template: azure-pipelines-test-azure.yaml
    parameters:
      pythonMajorVersion: '3'
      pythonMinorVersion: '7'
  - template: azure-pipelines-test-azure.yaml
    parameters:
      osType: 'macos'
  - template: azure-pipelines-test-azure.yaml
    parameters:
      osType: 'windows'
  - template: azure-pipelines-test-container.yaml
