parameters:
  osType: 'ubuntu'
  osVersion: 'latest'
  pythonMajorVersion: '3'
  pythonMinorVersion: '7'

jobs:
- job: 'test_azure_${{parameters.osType}}_${{parameters.pythonMajorVersion}}${{parameters.pythonMinorVersion}}'

  pool:
    vmImage: '${{parameters.osType}}-${{parameters.osVersion}}'

  strategy:
    matrix:
      StorageV2:
        storage.kind: 'StorageV2'
      Storage:
        storage.kind: 'Storage'
      BlobStorage:
        storage.kind: 'BlobStorage'

  steps:
  - template: azure-pipelines-install.yaml
    parameters:
      pythonMajorVersion: '${{parameters.pythonMajorVersion}}'
      pythonMinorVersion: '${{parameters.pythonMinorVersion}}'

  - script: python -m tests.test_storage azure --password "$(auth_password)" --tenant "$(auth_tenant)" --username "$(auth_username)" --subscription "$(auth_subscription)" --kind "$(storage.kind)"
    displayName: 'Run live storage tests'
    condition: and(succeeded(), ne(variables['auth_password'], ''), contains(variables['storage.kind'], 'Storage'))
