parameters:
  osType: 'ubuntu'
  osVersion: 'latest'
  pythonMajorVersion: '3'
  pythonMinorVersion: '7'
  storageKind: 'StorageV2'

jobs:
- job: 'test_${{parameters.storageKind}}_${{parameters.osType}}_${{parameters.pythonMajorVersion}}${{parameters.pythonMinorVersion}}'

  pool:
    vmImage: '${{parameters.osType}}-${{parameters.osVersion}}'

  steps:
  - template: azure-pipelines-install.yaml
    parameters:
      pythonMajorVersion: '${{parameters.pythonMajorVersion}}'
      pythonMinorVersion: '${{parameters.pythonMinorVersion}}'

  - script: python -m tests.test_storage azure --password "$(auth_password)" --tenant "$(auth_tenant)" --username "$(auth_username)" --subscription "$(auth_subscription)" --kind "${{parameters.storageKind}}"
    displayName: 'Run live storage tests'
    condition: and(succeeded(), ne(variables['auth_password'], ''))
