parameters:
  osType: ''

jobs:
- job: 'test_${{parameters.osType}}'

  pool:
    vmImage: '${{parameters.osType}}-latest'

  strategy:
    matrix:
      Python27-StorageV2:
        storage.kind: 'StorageV2'
        python.version: '2.7'
      Python37-StorageV2:
        storage.kind: 'StorageV2'
        python.version: '3.7'
      Python37-Storage:
        storage.kind: 'Storage'
        python.version: '3.7'
      Python37-BlobStorage:
        storage.kind: 'BlobStorage'
        python.version: '3.7'
      Python37-Azurite:
        storage.kind: 'azurite'
        python.version: '3.7'
      Python37-IotEdge:
        storage.kind: 'iotedge'
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip setuptools
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python -m pip install https://github.com/$(libcloud_repo)/archive/$(libcloud_version).zip
    displayName: 'Install $(libcloud_version) from $(libcloud_repo)'

  - script: python -m tests.test_storage new-azure-storage --password "$(auth_password)" --tenant "$(auth_tenant)" --username "$(auth_username)" --subscription "$(auth_subscription)" --kind "$(storage.kind)"
    displayName: 'Run live storage tests'
    condition: and(succeeded(), ne(variables['auth_password'], ''), contains(variables['storage.kind'], 'Storage'))
    continueOnError: true

  - script: python -m tests.test_storage "$(storage.kind)"
    displayName: 'Run local storage tests'
    condition: not(contains(variables['storage.kind'], 'Storage'))
    continueOnError: true
