trigger:
- master

stages:

- stage: lint
  jobs:
  - template: azure-pipelines-lint.yaml

- stage: test
  jobs:
  - template: azure-pipelines-test.yaml
    parameters:
      osType: 'ubuntu'
  - template: azure-pipelines-test.yaml
    parameters:
      osType: 'macos'
  - template: azure-pipelines-test.yaml
    parameters:
      osType: 'windows'
