jobs:
- job: lint

  pool:
    osType: 'ubuntu-latest'

  steps:
  - template: azure-pipelines-install.yaml

  - script: python -m pip install -r requirements-dev.txt
    displayName: 'Install dev dependencies'

  - script: invoke lint
    displayName: 'Run linters'
